### ISSUE TITLE
Meteor server crashes when adding package

### ISSUE THREAD

**Issue by Tim-W** [nate-strauser/meteor-x-editable-bootstrap#34]
When adding this package to my package list, I'm getting the following error. Afterwards, my Meteor server shuts down.

```
Changes to your project's package version selections:
                                              
natestrauser:x-editable-bootstrap  added, version 1.5.2_2

=> Meteor server restarted                    
http.js:732
    throw new Error('Can\'t render headers after they are sent to the client.'
          ^
Error: Can't render headers after they are sent to the client.
  at ServerResponse.OutgoingMessage._renderHeaders (http.js:732:11)
  at ServerResponse.writeHead (http.js:1153:20)
  at ProxyServer.<anonymous> (/home/tim/.meteor/packages/meteor-tool/.1.1.3.1ezhh7++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/run-proxy.js:96:21)
  at ProxyServer.emit (/home/tim/.meteor/packages/meteor-tool/.1.1.3.1ezhh7++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/http-proxy/node_modules/eventemitter3/index.js:100:27)
  at ClientRequest.proxyError (/home/tim/.meteor/packages/meteor-tool/.1.1.3.1ezhh7++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:140:16)
  at ClientRequest.emit (events.js:117:20)
  at Socket.socketOnData (http.js:1593:9)
  at TCP.onread (net.js:528:27)
```
I guess this has something to do with Bootstrap loading more than once?

My .meteor/packages file:
```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-platform
insecure
meteorhacks:fast-render
twbs:bootstrap
aldeed:collection2
aldeed:simple-schema
aldeed:autoform
mquandalle:jade
accounts-base
accounts-password
reactive-var
iron:router
hitchcott:ez-modal
zimme:iron-router-active
rajit:bootstrap3-datepicker
aldeed:autoform-bs-datepicker
aslagle:reactive-table
anti:i18n
dburles:collection-helpers
reactive-dict
msavin:mongol
autopublish
manuel:viewmodel-explorer
manuel:viewmodel
coffee:script
babrahams:editable-list
yogiben:autoform-modals
babrahams:editable-text
natestrauser:x-editable-bootstrap
```

**Comment by nate-strauser** [comment]
@Tim-W can you confirm if this is still happening?  if so, could you provide minimally reproducing example app?

**Comment by Tim-W** [comment]
@nate-strauser I added the package to one of my other projects. The meteor server does crash after adding the package, but this time with a different error message. 

```
/Users/timwissel/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/pathwatcher/lib/main.js:66
      this.handle = binding.watch(this.path);
                            ^
Error: Unable to watch path
  at HandleWatcher.start (/Users/timwissel/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/pathwatcher/lib/main.js:66:29)
  at /Users/timwissel/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/pathwatcher/lib/main.js:43:25
  at Object.oncomplete (fs.js:108:15)
```
